feat: add users and items
Avseenkov/java-shareit pull request #1
Opened 2023-01-10 20:42 UTC by Avseenkov

2023-01-11 08:07 UTC, LexLippi requested changes
Привет!

Хорошая работа, но есть некоторое количество замечаний, которые необходимо поправить!

Желаю удачи!!!

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   */
Такие комментарии не стоит оставлять, если реализовано то, что указано в `to-do`, чтобы все `to-do` в коде поддерживались в актуальном состоянии, и можно было с помощью поиска быстро и просто найти требующиеся актуальные доработки.

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    Long id;
1. Почему здесь нет модификатора доступа? Даже `protected` лучше прописывать явно
2. Я противник использования разных модификаторов в рамках одного объекта. Здесь это не является критическим местом, но можно подумать (не обязательно), как организовать код таким образом, чтобы все модификаторы были одинаковыми

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemStorage itemStorage;
1. Лучше прописывать модификаторы явно
2. Почему используем одно хранилище, и один сервис? По сути для одних и тех же целей. Стоит использовать хранилища в обоих случаях.

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +public class ItemService {
Вообще для этого стоит использовать шаблон интерфейс + реализация, чтобы абстрагировать контроллер от конкретной реализации `Service`,  поскольку нам может понадобиться другая реализация (например, кэширующая данные).

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    }
Не хватает `slash` в начале строки с маппингом: `/{itemId}`, например

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (query.isBlank() || query.isEmpty()) return List.of();
1. Если `query` это `null`, то здесь может произойти `NullPointerException`, что кажется не очень хорошо, потому что это довольно неожиданно с точки зрения программиста, который не писал код, а который по каким-то причинам когда-то к нему обратиться. Лучше явную проверку на `null` добавить
2. В соответствии с Java Google Code Style я рекомендую всенда использовать фигурные скобки даже когда они опциональны:
https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (itemDto.getDescription() != null) item.setDescription(itemDto.getDescription());
аналогично про скобки

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/storage/MemoryItemStorage.java
> +        return items.containsKey(id) ? Optional.of(items.get(id)) : Optional.empty();
Можно использовать конструкцию `Optional.ofNullable(items.get(id))`, чтобы обойтись без тернарного оператора, а делает она ровно тоже самое

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/storage/MemoryItemStorage.java
> +        items.put(item.getId(), item);
Лучше в случае если идентификатор уже установлен не сохранять его в хранилище, а выбрасывать ошибку. Иначе это может привести к нарушению целостности генератора идентфикаторов, они могут задублироваться, и данные могут пропасть, что очень не хорошо

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    LocalDate created;
А здесь не стоит добавить валидирующие аннотации и модификаторы?

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/MemoryStorage.java
> +        if (user.getId() == null) user.setId(++ids);
Замечание аналогичные тем, что были в `ItemController`

2023-01-11 08:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public class UserService {
Аналогичное замечание про интерфейс

2023-01-25 06:48 UTC, Avseenkov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemStorage itemStorage;
Использую хранилище так как этот сервис связан с хранилищем, для других сущностей использую сервис, так как в сервисе прописана логика, по выдаче ошибок если, что-то не найдено. Чтобы не дублировать проверки.

2023-01-25 07:37 UTC, Avseenkov commented on src/main/java/ru/practicum/shareit/item/storage/MemoryItemStorage.java
> +        items.put(item.getId(), item);
Это реализация через Map, разве он может здесь задублироваться?

2023-01-26 06:13 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/storage/MemoryItemStorage.java
> +        items.put(item.getId(), item);
В данном случае нет.

Но я имел в виду, что раз уж у нас есть отдельный метод для `insert` и отдельный для `update`, то лучше разделять их логику. То есть проверять, что в `insert` всегда приходит задача без идентификатора, и таким образом гарантировать, что она создается впервые, а в `update` всегда с идентификатором.

Иначе это может привести к side-эффектам, и ошибкам, которые потом будет сложнее отловить и покрыть тестами. 
Это в некотором смысле можно понимать, как Single Responsibility Principle из SOLID. То есть мы хотим, чтобы у метода была ровно одна функция: вставить запись, или обновить запись. Не хотим здесь метод, который вставляет или обновляет запись.

Но это не критично, давай оставим так, если что, может я уже загоняюсь)

2023-01-26 06:15 UTC, LexLippi approved these changes
Привет!

Хорошая работа! 
Ответил на твой комментарий, можешь посмотреть, и по желанию сделать, так как я описал, либо оставить так как есть.

Задачу принимаю.
Желаю удачи в следующих спринтах!

2023-01-26 07:19 UTC, merged