feat:  implementation 15
Avseenkov/java-shareit pull request #3
Opened 2023-03-21 20:06 UTC by Avseenkov

2023-03-24 09:05 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара небольших замечаний, которые необходимо исправить!

2023-03-24 09:05 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +    private ItemServiceImpl itemService;
В тестах нет необходимости в явных модификаторах доступа

2023-03-24 09:05 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");
Это можно сделать статическим полем класса, чтобы каждый раз не инициализировать локальную переменную

2023-03-24 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +public class ItemRequestMapper {
`mapper` лучше оформлять в виде синглтона:

https://en.wikipedia.org/wiki/Singleton_pattern

Как вариант это можно сделать с помощью `enum`:

https://www.geeksforgeeks.org/advantages-and-disadvantages-of-using-enum-as-singleton-in-java/

2023-03-24 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    @NotBlank
В аннотации `NotBlank` уже содержится аннотация `NotNull`, так что двойная проверка - бессмысленна

2023-03-24 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Comment> comments = (List<Comment>) item.getComments();
Лучше сразу хранить как список, и не использовать такого вида кастинг. Потому что потенциально там может быть и не список, Idea (если ты разрабатываешь в ней) должна ругаться на "unchecked cast"

2023-03-27 07:20 UTC, Avseenkov commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +public class ItemRequestMapper {
Не понял почему здесь лучше использовать singleton?  https://www.baeldung.com/lombok-custom-annotation , говорится, что в таких случаях лучше использовать статические методы.

2023-03-27 21:18 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +public class ItemRequestMapper {
Ага, я имею в виду, чтобы у этого класса нельзя было создавать инстансы, это может привести к различным неприятным ситуациям. Это можно сделать, например, сделав конструктор по умолчанию приватным:

```java
private ItemRequestMapper() {
}
```

2023-03-27 21:21 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2023-03-30 06:47 UTC, merged